name: NET

on:
  push:
    branches: [ "master","cai", "main"]
    
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
           submodules: 'recursive'
           
      - name: Initialize .NET 6
        uses: actions/setup-dotnet@v3
        env:
          DOTNET_CLI_UI_LANGUAGE: zh-CN
        with:
          dotnet-version: 6.0.x
          
      - name: Build Plugin
        run: |
          dotnet build Plugin.sln -c Release

      - name: Initialize Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Install Pandoc
        run: 
          sudo apt-get install pandoc
        env:
          PYTHONIOENCODING: 'utf-8'
        
      - name: Install TeX Live
        run: |
          sudo apt-get install -y texlive-xetex

      - name: Package
        run: 
          sudo python BuildHelper.py Release
        env:
          PYTHONIOENCODING: 'utf-8'
      
      - name: Temporary Upload Plugin
        uses: actions/upload-artifact@v3
        with:
          name: Plugins
          path: Plugins.zip

      - name: Prepare Release Files
        uses: actions/upload-artifact@v3
        with:
          name: Plugins
          path: Plugins.zip
          
  LatestRelease:
    name: Latest Release
    runs-on: ubuntu-latest
    needs: Build
    permissions:
         contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Changelog
        id: external_changelog_second
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: "Config/Config_Rep.json"
            #cache: ${{ steps.external_changelog_collect.outputs.cache }}
      - name: Echo External Repo Configuration Changelog
        env:
          CHANGELOG: ${{ steps.external_changelog_second.outputs.changelog }}
          CHANGELOG_SECOND: ${{ steps.external_changelog_second.outputs.changelog }}
        run: |
          echo ${{ steps.external_changelog_collect.outputs.cache }}
          echo "First:"
          echo "$CHANGELOG"

          echo "Second:"
          echo "$CHANGELOG_SECOND"
          
      - name: Update Tag
        run: |
          git tag -f V1.0.0.0
          git push -f origin V1.0.0.0
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Plugins
          path: ./bin
      - name: Update Latest Release
        uses: ncipollo/release-action@v1
        with:
          tag: V1.0.0.0
          name: "Latest Version"
          body: "ğŸš€ æ¯æ¬¡ä»“åº“æ›´æ–°ï¼Œæˆ‘ä»¬éƒ½ä¼šåœ¨è¿™é‡Œå‘å¸ƒæœ€æ–°çš„Releaseã€‚è¯·æ³¨æ„ï¼Œè¿™ä¸ªä»“åº“åªæœ‰ä¸€ä¸ªReleaseï¼Œæ‰€ä»¥ä½ æ€»æ˜¯èƒ½åœ¨è¿™é‡Œæ‰¾åˆ°æœ€æ–°çš„ç‰ˆæœ¬ã€‚\nğŸ“¦ ä½ å¯ä»¥åœ¨é¡µé¢çš„æœ€åº•éƒ¨æ‰¾åˆ°æ’ä»¶åŒ…çš„ä¸‹è½½é“¾æ¥ã€‚ä¸‹è½½å®Œæˆåï¼Œä½ éœ€è¦ä½¿ç”¨ZIPå‹ç¼©å·¥å…·è¿›è¡Œè§£å‹ã€‚\n${{steps.external_changelog_second.outputs.changelog}}"
          artifacts: |
            ./bin/*
          allowUpdates: true
          removeArtifacts: true
          
      
         
  ClearTempArtifacts:
    name: Clear Temp Artifacts
    if: always()
    runs-on: ubuntu-latest
    needs:
      - LatestRelease
    permissions:
      actions: write
    steps:
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            Plugins
