name: æ’ä»¶å‘å¸ƒ

on:
  push:
    branches: [ "master","cai"]
    
jobs:
  Build:
    runs-on: ubuntu-latest
    name: æ„å»ºæ’ä»¶
    steps:
      - uses: actions/checkout@v4
           
      - name: åˆå§‹åŒ–.NET 6
        uses: actions/setup-dotnet@v4
        env:
          DOTNET_CLI_UI_LANGUAGE: zh-CN
        with:
          dotnet-version: 6.0.x

      - name: æ›´æ–°å­æ¨¡å—
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo ${{ github.repository }}
          if [ "${{ github.repository }}" = "UnrealMultiple/TShockPlugin" ]; then
            git pull
            git submodule update --init
            git submodule update --remote
            git add .
            if git diff --staged --quiet; then
              echo "è·³è¿‡æ›´æ–°ï¼šå­æ¨¡å—æ²¡æœ‰å˜åŒ–"
            else
              git commit -m "è‡ªåŠ¨æ›´æ–°å­æ¨¡å— [skip ci]"
              git push
            fi
          else
            echo "éUnrealMultiple/TShockPluginä»“åº“ï¼Œè·³è¿‡æäº¤."
          fi
          
      - name: å®‰è£…æ„å»ºä¾èµ–
        run: |
          sudo apt install -y gettext
          
      - name: æ„å»ºæ’ä»¶
        run: |
          dotnet build Plugin.sln -c Release
                
  
      - name: ä¸‹è½½PluginInfoLoader
        run: |
          wget -q https://github.com/ACaiCat/PluginInfoLoaderr/releases/download/v1.0.0.0/linux-x64.zip
          unzip -qq linux-x64.zip
      
      - name: è¿è¡ŒTShockç”ŸæˆPlugins.json
        timeout-minutes: 3
        run: |
          cp ./out/Release/*.dll ./linux-x64/ServerPlugins/
          cd linux-x64
          chmod +x TShock.Server
          ./TShock.Server
  
      - name: ç§»åŠ¨Plugins.json
        run: |
          mv linux-x64/Plugins.json ./

      - name: è‡ªåŠ¨æ›´æ–°Plugins.json
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo ${{ github.repository }}
          if [ "${{ github.repository }}" = "UnrealMultiple/TShockPlugin" ]; then
            git add Plugins.json
            if git diff --staged --quiet; then
              echo "è·³è¿‡æ›´æ–°ï¼šæ²¡æœ‰æ’ä»¶ç‰ˆæœ¬å˜åŒ–"
            else
              git commit -m "è‡ªåŠ¨æ›´æ–°Plugins.json [skip ci]"
              git pull
              git push
            fi
          else
            echo "éUnrealMultiple/TShockPluginä»“åº“ï¼Œè·³è¿‡æäº¤."
          fi

      - name: åˆå§‹åŒ–Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: æ‰“åŒ…
        run: 
          sudo python BuildHelper.py Release
        env:
          PYTHONIOENCODING: 'utf-8'
      
      - name: ä¸Šä¼ ä¸´æ—¶æ’ä»¶åŒ…
        uses: actions/upload-artifact@v4
        with:
          name: Plugins
          path: Plugins.zip
          
  LatestRelease:
    name: å‘å¸ƒæ’ä»¶
    runs-on: ubuntu-latest
    needs: Build
    permissions:
         contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: è·å–æ›´æ–°æ—¥å¿—
        id: external_changelog_second
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: "Config/Config_Rep.json"
            #cache: ${{ steps.external_changelog_collect.outputs.cache }}
      - name: ç”Ÿæˆæ›´æ–°æ—¥å¿—
        env:
          CHANGELOG: ${{ steps.external_changelog_second.outputs.changelog }}
          CHANGELOG_SECOND: ${{ steps.external_changelog_second.outputs.changelog }}
        run: |
          echo ${{ steps.external_changelog_collect.outputs.cache }}
          echo "First:"
          echo "$CHANGELOG"

          echo "Second:"
          echo "$CHANGELOG_SECOND"
          
      - name: æ›´æ–°å‘å¸ƒæ ‡ç­¾
        run: |
          git tag -f V1.0.0.0
          git push -f origin V1.0.0.0
      - name: ä¸‹è½½ä¸´æ—¶æ’ä»¶åŒ…
        uses: actions/download-artifact@v4
        with:
          name: Plugins
          path: ./bin
      - name: å‘å¸ƒæ’ä»¶åŒ…
        uses: ncipollo/release-action@v1
        with:
          tag: V1.0.0.0
          name: "æœ€æ–°ç‰ˆæœ¬"
          body: "# æ’ä»¶ä¸‹è½½å’Œæ›´æ–°æ—¥å¿—\n###  ğŸ“… æ¯æ¬¡ä»“åº“æ›´æ–°ï¼Œæˆ‘ä»¬éƒ½ä¼šåœ¨è¿™é‡Œå‘å¸ƒæœ€æ–°çš„Releaseã€‚è¯·æ³¨æ„ï¼Œè¿™ä¸ªä»“åº“åªæœ‰ä¸€ä¸ªReleaseï¼Œæ‰€ä»¥ä½ æ€»æ˜¯èƒ½åœ¨è¿™é‡Œæ‰¾åˆ°æœ€æ–°çš„ç‰ˆæœ¬ã€‚\n### ğŸ“–æ–‡æ¡£å·²ç»ä»¥PDFçš„å½¢å¼é™„åœ¨æ’ä»¶åŒ…ä¸­ã€‚æ›´æ¨èä½ ç›´æ¥åœ¨ä»“åº“ä¸»é¡µä¸­çš„[æ’ä»¶åˆ—è¡¨](https://github.com/Controllerdestiny/TShockPlugin?tab=readme-ov-file#%E5%B7%B2%E6%94%B6%E9%9B%86%E6%8F%92%E4%BB%B6)ï¼Œç‚¹å‡»æ’ä»¶åè·³è½¬åˆ°æ¯ä¸ªæ’ä»¶çš„è¯¦ç»†æ–‡æ¡£ã€‚\n###  ğŸ“¦ ä½ å¯ä»¥åœ¨é¡µé¢çš„`æœ€åº•éƒ¨â†“â†“â†“`æ‰¾åˆ°æ’ä»¶åŒ…çš„ä¸‹è½½é“¾æ¥ã€‚ä¸‹è½½å®Œæˆåï¼Œä½ éœ€è¦ä½¿ç”¨`ZIPå‹ç¼©å·¥å…·`è¿›è¡Œè§£å‹ã€‚\n> [!CAUTION]\n>**è¯·ä½ `è¯¦ç»†`çš„çœ‹`ä¸Šé¢çš„è¯´æ˜`ï¼Œä¸è¦åˆ°å¤„é—®`æ’ä»¶æ€ä¹ˆç”¨`ã€`ZIPå¦‚ä½•è§£å‹`ã€`PDFæ€ä¹ˆæ‰“å¼€`**\n<details>\n<summary>æ›´æ–°æ—¥å¿—</summary>\n\n${{steps.external_changelog_second.outputs.changelog}}</details>"
          artifacts: |
            ./bin/*
          allowUpdates: true
          removeArtifacts: true
          
      
         
  ClearTempArtifacts:
    name: æ¸…ç†ä¸´æ—¶æ–‡ä»¶
    if: always()
    runs-on: ubuntu-latest
    needs:
      - LatestRelease
    permissions:
      actions: write
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            Plugins
