name: 拉取请求检查

on:
  pull_request:
    branches: 
      - master
      - cai
  push:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建插件
    steps:
      - uses: actions/checkout@v4
        with:
           submodules: 'recursive'
           
      - name: 初始化.NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
          
      - name: 构建插件
        run: |
          dotnet build Plugin.sln
          
      - name: 初始化Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown imgkit

      - name: 安装beautifulsoup4 和 wkhtmltopdf
        run: |
            sudo pip install beautifulsoup4
            sudo apt-get install wkhtmltopdf
          
      - name: 打包插件
        run: python BuildHelper.py Debug
        env:
          PYTHONIOENCODING: 'utf-8'
      
      - name: 上传插件包
        uses: actions/upload-artifact@v4
        with:
          name: Plugin
          path: out/Debug/*
